type Lang = 'en' | 'ha' | 'pcm'

const translations = {
  en: {
    // Nav
    home: 'Home', services: 'Services', products: 'Products', trending: 'Trending',
    sell: 'Get Started', dashboard: 'Dashboard', profile: 'Profile', messages: 'Messages',
    sellerDashboard: 'Seller Dashboard', orders: 'Orders', wishlist: 'Wishlist',
    compare: 'Compare', savedSearches: 'Saved Searches', adminDashboard: 'Admin Dashboard',
    logout: 'Logout', login: 'Login', searchPlaceholderNav: 'Search products, categories...',
    // Hero
    tagline: 'Your #1 Site to Find Trusted Artisans in Jos',
    heroTitle: 'Find the Right', heroHighlight: 'Artisan', heroSubtitle: 'When You Need One',
    heroDescription: 'Plumbers, electricians, bakers, mechanics & more — find trusted artisans in Jos, fast.',
    searchPlaceholder: 'Search for a service... e.g. plumber, electrician',
    popular: 'Popular', plumbing: 'Plumbing', electricians: 'Electricians', acRepair: 'AC Repair', bakers: 'Bakers',
    // Sections
    ourServices: 'Our Services', findA: 'Find a', findServiceProvider: 'Service Provider',
    trustedProfessionals: 'Trusted professionals in Jos ready to get the job done',
    liveServiceMap: 'Live Service Map', findServicesNear: 'Find Services', nearYou: 'Near You',
    mapDesc: 'Browse verified service providers across Jos on the map. Click any pin to contact them instantly.',
    browseAllServices: 'Browse All Services',
    featuredListings: 'Featured Listings', discoverServices: 'Discover amazing services from local providers',
    viewAll: 'View All', noListingsYet: 'No listings yet', beFirstToList: 'Be the first to list your service or product',
    listYourService: 'List Your Service',
    // How it works
    simpleProcess: 'Simple Process', howItWorks: 'How It Works',
    howItWorksDesc: 'Whether you\'re looking for a service or offering one — JosMKT makes it simple.',
    forCustomers: 'For Customers', forProviders: 'For Providers',
    registerBusinessCta: 'Register Your Business — It\'s Free',
    // Stats
    monthlyViews: 'Monthly Views', businesses: 'Businesses Listed', growthRate: 'Growth Rate', happyCustomers: 'Happy Customers',
    // FAQ
    faqTitle: 'Frequently Asked Questions', faqSubtitle: 'Everything you need to know about our services',
    faq1Q: 'How does JosMKT boost my business visibility?', faq1A: 'We list your business on our platform seen by thousands of active buyers in Jos. Our promotion packages include featured listings, social media shoutouts, and targeted ads.',
    faq2Q: 'What promotion packages are available?', faq2A: 'We offer Basic (free listing), Standard (featured placement + social media), and Premium (full promotion suite with analytics). Contact us for custom packages.',
    faq3Q: 'How do I list my business or service?', faq3A: "Click 'Get Started' in the navigation, fill out your business profile, and choose a promotion plan. Your listing goes live within 24 hours.",
    faq4Q: 'Is there a free option?', faq4A: 'Yes! Our Basic listing is completely free. You can upgrade anytime to get more visibility and promotion features.',
    faq5Q: 'Can I track how my business is performing?', faq5A: 'Absolutely! Our dashboard shows views, clicks, inquiries, and engagement metrics so you can measure your growth.',
    faq6Q: 'What areas does JosMKT cover?', faq6A: 'We cover all areas in Jos including Bukuru, Rayfield, Terminus, Lamingo, and surrounding areas in Plateau State.',
    // CTA
    readyToGrow: 'Ready to Grow Your Business?', joinThousands: 'Join thousands of service providers and reach customers across Jos',
    getStartedFree: 'Get Started Free',
    // Language
    language: 'Language', english: 'English', hausa: 'Hausa', pidgin: 'Pidgin',
    // Footer
    footerDesc: 'Showcase your business to thousands of buyers in Jos — get discovered, get promoted, get results',
    categories: 'Categories', company: 'Company', contactUs: 'Contact Us',
    electronics: 'Electronics', fashion: 'Fashion', foodCatering: 'Food & Catering', techRepairs: 'Tech & Repairs',
    aboutUs: 'About Us', contact: 'Contact Us', privacy: 'Privacy Policy', terms: 'Terms of Service',
    becomeSeller: 'Become a Seller', allRightsReserved: 'All rights reserved.',
    poweredBy: 'Powered by',
    // Newsletter
    newsletterTitle: 'Stay Updated with JosMKT',
    newsletterDesc: 'Get weekly tips, new service providers, and exclusive deals delivered to your inbox.',
    emailPlaceholder: 'Enter your email address', subscribe: 'Subscribe',
    subscribedSuccess: 'Subscribed successfully!', noSpam: 'Free forever. No spam. Unsubscribe anytime.',
    // Services page
    allServices: 'All Services', verifiedProfessionals: 'Verified professionals in Jos',
    searchServices: 'Search by name, location...', providersFound: 'provider found', providersFoundPlural: 'providers found',
    providersPinned: 'providers pinned', sortedByDistance: 'Sorted by Distance', findNearestToMe: 'Find Nearest to Me',
    noResultsFor: 'No results for', noProvidersIn: 'No providers yet in', clearSearch: 'Clear Search',
    registerYourBusiness: 'Register Your Business', areYouProvider: 'Are you a service provider?',
    listBusinessDesc: 'Join thousands of professionals getting discovered by customers in Jos every day.',
    call: 'Call', whatsapp: 'WhatsApp', verified: 'Verified', kmAway: 'km away',
    back: 'Back', location: 'Location', getDirections: 'Get Directions',
    about: 'About', gallery: 'Gallery', needThisService: 'Need this service?',
    contactDirectly: 'Contact', directly: 'directly and get started today.',
    providerNotFound: 'Provider not found',
    // Become seller
    registerBusiness: 'Register Your Business', getStartedOnJosMKT: 'Get Started on JosMKT',
    becomeSellerdesc: 'List your service or business and get discovered by thousands of customers in Jos',
    businessName: 'Business / Service Name *', category: 'Category *', describeYourBusiness: 'Describe your business *',
    phoneWhatsapp: 'Phone / WhatsApp *', location: 'Location *', pinExactLocation: 'Pin Your Exact Location',
    pinLocationDesc: 'Helps customers find you on the map', locationPinned: 'Location Pinned ✓', useMyGPS: 'Use My GPS',
    experience: 'Experience', priceRange: 'Price Range', businessLogo: 'Business Logo / Photo',
    workSamples: 'Work Samples / Gallery (optional)', identityVerification: 'Identity Verification (Required)',
    verificationDesc: 'To protect customers from scams, we verify every service provider before approval.',
    govId: 'Government-issued ID', govIdDesc: 'NIN slip, Voter\'s card, Driver\'s license, International passport, or Student ID',
    selfieWithId: 'Selfie holding your ID', selfieDesc: 'Take a clear photo of yourself holding the same ID document',
    uploadYourId: 'Upload your ID', uploadSelfie: 'Take / upload selfie with ID',
    idUploaded: 'ID uploaded ✓', selfieUploaded: 'Selfie uploaded ✓',
    submitting: 'Submitting...', submitApplication: 'Submit Application',
    applicationSubmitted: 'Application Submitted!',
    applicationDesc: 'Your business registration is under review. We\'ll contact you once approved and your profile will be live on JosMKT.',
    backToHome: 'Back to Home', reviewTime: 'Your application will be reviewed within 24 hours.',
    selectCategory: 'Select your category', selectLocation: 'Select location',
    experiencePlaceholder: 'e.g. 3 years', priceRangePlaceholder: 'e.g. ₦5,000 - ₦50,000',
    uploading: 'Uploading...',
  },
  ha: {
    // Nav
    home: 'Gida', services: 'Ayyuka', products: 'Kayayyaki', trending: 'Shahararru',
    sell: 'Fara', dashboard: 'Shafin Sarrafa', profile: 'Bayanan ku', messages: 'Saƙonni',
    sellerDashboard: 'Shafin Mai Sayarwa', orders: 'Oda', wishlist: 'Abubuwan da nake so',
    compare: 'Kwatanta', savedSearches: 'Bincike da aka Adana', adminDashboard: 'Shafin Admin',
    logout: 'Fita', login: 'Shiga', searchPlaceholderNav: 'Nemo kayayyaki, nau\'i...',
    // Hero
    tagline: 'Shafin ku na #1 don Nemo Masu Sana\'a a Jos',
    heroTitle: 'Nemo', heroHighlight: 'Ɗan Sana\'a', heroSubtitle: 'Lokacin da kuke Bukata',
    heroDescription: 'Masu gyaran bututu, masu lantarki, masu yin burodi, injiniyoyi da sauransu — nemo masu sana\'a da ake amincewa da su a Jos, cikin sauri.',
    searchPlaceholder: 'Nemo sabis... misali mai gyaran bututu, mai lantarki',
    popular: 'Shahararru', plumbing: 'Bututu', electricians: 'Lantarki', acRepair: 'Gyaran AC', bakers: 'Masu Burodi',
    // Sections
    ourServices: 'Ayyukanmu', findA: 'Nemo', findServiceProvider: 'Mai Bayar da Sabis',
    trustedProfessionals: 'Ƙwararru masu aminci a Jos da suke shirye su yi aiki',
    liveServiceMap: 'Taswirar Sabis', findServicesNear: 'Nemo Sabis', nearYou: 'Kusa da ku',
    mapDesc: 'Duba masu bayar da sabis da aka tabbatar a Jos a taswirar. Danna kowane pin don tuntuɓe su.',
    browseAllServices: 'Duba Duk Ayyuka',
    featuredListings: 'Jerin da aka Tallata', discoverServices: 'Gano ayyuka masu kyau daga masu bayarwa na gida',
    viewAll: 'Duba Duka', noListingsYet: 'Babu jeri har yanzu', beFirstToList: 'Ku zama na farko',
    listYourService: 'Jera Sabis ɗin ku',
    // How it works
    simpleProcess: 'Tsari Mai Sauƙi', howItWorks: 'Yadda Yake Aiki',
    howItWorksDesc: 'Ko kuna neman sabis ko kuna bayar da shi — JosMKT yana sauƙaƙa komai.',
    forCustomers: 'Don Abokan Ciniki', forProviders: 'Don Masu Bayarwa',
    registerBusinessCta: 'Yi Rajistan Kasuwancin ku — Kyauta',
    // Stats
    monthlyViews: 'Kallon Wata', businesses: 'Kasuwanci', growthRate: 'Yawan Girma', happyCustomers: 'Abokan Ciniki',
    // FAQ
    faqTitle: 'Tambayoyin da Ake Yawan Yi', faqSubtitle: 'Duk abin da kuke bukata ku sani game da ayyukanmu',
    faq1Q: 'Ta yaya JosMKT ke ƙara ganin kasuwancina?', faq1A: 'Muna jera kasuwancin ku a dandamali ɗin mu wanda dubban masu saye a Jos ke gani.',
    faq2Q: 'Wane irin kunshin tallata ake da su?', faq2A: 'Muna ba da Basic (jerin kyauta), Standard, da Premium. Tuntuɓe mu don kunshin musamman.',
    faq3Q: 'Ta yaya zan jera kasuwancina?', faq3A: "Danna 'Fara' a cikin kewayawa, cika bayanan kasuwancin ku, kuma zaɓi shirin tallata.",
    faq4Q: 'Akwai zaɓi na kyauta?', faq4A: 'Eh! Jerin mu na Basic kyauta ne gaba ɗaya.',
    faq5Q: 'Zan iya bin diddigin yadda kasuwancina ke yi?', faq5A: 'Tabbas! Shafin sarrafa mu yana nuna kallon, dannawa, tambayoyi, da hulɗa.',
    faq6Q: 'Wane yanki ne JosMKT ke rufe?', faq6A: 'Muna rufe duk yankuna a Jos ciki har da Bukuru, Rayfield, Terminus, Lamingo.',
    // CTA
    readyToGrow: 'Kuna Shirye ku Girma Kasuwancin ku?', joinThousands: 'Ku shiga tare da dubban masu bayar da sabis a Jos',
    getStartedFree: 'Fara Kyauta',
    // Language
    language: 'Harshe', english: 'Turanci', hausa: 'Hausa', pidgin: 'Pidgin',
    // Footer
    footerDesc: 'Nuna kasuwancin ku ga dubban masu saye a Jos — a same ku, a tallata ku, ku sami sakamako',
    categories: 'Nau\'i', company: 'Kamfani', contactUs: 'Tuntuɓe mu',
    electronics: 'Lantarki', fashion: 'Tufafi', foodCatering: 'Abinci', techRepairs: 'Fasaha',
    aboutUs: 'Game da mu', contact: 'Tuntuɓe mu', privacy: 'Manufar Sirri', terms: 'Sharuɗɗan Amfani',
    becomeSeller: 'Zama Mai Sayarwa', allRightsReserved: 'Duk haƙƙoƙi an kiyaye su.',
    poweredBy: 'Ƙarfin',
    // Newsletter
    newsletterTitle: 'Kasance a Sani da JosMKT',
    newsletterDesc: 'Sami shawarwari na mako-mako, sabbin masu bayar da sabis, da kayayyakin musamman a imel ɗin ku.',
    emailPlaceholder: 'Shigar da adireshin imel ɗin ku', subscribe: 'Yi Rajista',
    subscribedSuccess: 'An yi rajista cikin nasara!', noSpam: 'Kyauta har abada. Babu spam. Fita daga rajista a kowane lokaci.',
    // Services page
    allServices: 'Duk Ayyuka', verifiedProfessionals: 'Ƙwararru masu aminci a Jos',
    searchServices: 'Nemo da suna, wuri...', providersFound: 'mai bayarwa an samu', providersFoundPlural: 'masu bayarwa an samu',
    providersPinned: 'masu bayarwa an ƙulla', sortedByDistance: 'An Tsara ta Nisa', findNearestToMe: 'Nemo Mafi Kusa da ni',
    noResultsFor: 'Babu sakamako don', noProvidersIn: 'Babu masu bayarwa a', clearSearch: 'Share Bincike',
    registerYourBusiness: 'Yi Rajistan Kasuwancin ku', areYouProvider: 'Kuna mai bayar da sabis?',
    listBusinessDesc: 'Ku shiga tare da dubban ƙwararru da ake gano su ta hanyar abokan ciniki a Jos kowace rana.',
    call: 'Kira', whatsapp: 'WhatsApp', verified: 'An Tabbatar', kmAway: 'km nesa',
    back: 'Koma', location: 'Wuri', getDirections: 'Nemo Hanya',
    about: 'Game da', gallery: 'Gidan Hoto', needThisService: 'Kuna buƙatar wannan sabis?',
    contactDirectly: 'Tuntuɓi', directly: 'kai tsaye kuma fara yau.',
    providerNotFound: 'Ba a sami mai bayarwa ba',
    // Become seller
    registerBusiness: 'Yi Rajistan Kasuwancin ku', getStartedOnJosMKT: 'Fara a JosMKT',
    becomeSellerdesc: 'Jera sabis ko kasuwancin ku kuma dubban abokan ciniki a Jos za su same ku',
    businessName: 'Sunan Kasuwanci / Sabis *', category: 'Nau\'i *', describeYourBusiness: 'Bayyana kasuwancin ku *',
    phoneWhatsapp: 'Waya / WhatsApp *', location: 'Wuri *', pinExactLocation: 'Ƙulla Wurin ku na Daidai',
    pinLocationDesc: 'Yana taimaka wa abokan ciniki su same ku a taswirar', locationPinned: 'An Ƙulla Wuri ✓', useMyGPS: 'Yi amfani da GPS na',
    experience: 'Ƙwarewa', priceRange: 'Kewayon Farashi', businessLogo: 'Tambarin Kasuwanci / Hoto',
    workSamples: 'Samfuran Aiki / Gidan Hoto (zaɓi)', identityVerification: 'Tabbatar da Asali (Wajibi)',
    verificationDesc: 'Don kare abokan ciniki daga zamba, muna tabbatar da kowane mai bayar da sabis kafin amincewa.',
    govId: 'ID da Gwamnati ta Bayar', govIdDesc: 'Takarda NIN, Katin Zaɓe, Lasisi, Fasfo, ko ID ɗin Ɗalibi',
    selfieWithId: 'Selfie yana riƙe da ID ɗin ku', selfieDesc: 'Ɗauki hoton ku a bayyane yana riƙe da takarda ɗaya',
    uploadYourId: 'Loda ID ɗin ku', uploadSelfie: 'Ɗauki / loda selfie tare da ID',
    idUploaded: 'An loda ID ✓', selfieUploaded: 'An loda selfie ✓',
    submitting: 'Ana aika...', submitApplication: 'Aika Aikace-aikace',
    applicationSubmitted: 'An Aika Aikace-aikacen!',
    applicationDesc: 'Ana duba rajistan kasuwancin ku. Za mu tuntuɓe ku da zarar an amince kuma bayanan ku za su kasance a kan JosMKT.',
    backToHome: 'Koma Gida', reviewTime: 'Za a duba aikace-aikacen ku cikin awanni 24.',
    selectCategory: 'Zaɓi nau\'in ku', selectLocation: 'Zaɓi wuri',
    experiencePlaceholder: 'misali shekaru 3', priceRangePlaceholder: 'misali ₦5,000 - ₦50,000',
    uploading: 'Ana loda...',
  },
  pcm: {
    // Nav
    home: 'Home', services: 'Services', products: 'Products', trending: 'Trending',
    sell: 'Start Now', dashboard: 'Dashboard', profile: 'Profile', messages: 'Messages',
    sellerDashboard: 'Seller Dashboard', orders: 'Orders', wishlist: 'Tins Wey I Like',
    compare: 'Compare', savedSearches: 'Saved Searches', adminDashboard: 'Admin Dashboard',
    logout: 'Comot', login: 'Enter', searchPlaceholderNav: 'Search products, categories...',
    // Hero
    tagline: 'Your #1 Site to Find Correct Artisans for Jos',
    heroTitle: 'Find the', heroHighlight: 'Correct Artisan', heroSubtitle: 'When You Need Am',
    heroDescription: 'Plumber, electrician, baker, mechanic & more — find people wey you fit trust for Jos, sharp sharp.',
    searchPlaceholder: 'Search for service... e.g. plumber, electrician',
    popular: 'Popular', plumbing: 'Plumbing', electricians: 'Electricians', acRepair: 'AC Repair', bakers: 'Bakers',
    // Sections
    ourServices: 'Our Services', findA: 'Find', findServiceProvider: 'Service Provider',
    trustedProfessionals: 'Trusted people for Jos wey ready to do the work',
    liveServiceMap: 'Live Service Map', findServicesNear: 'Find Services', nearYou: 'Near You',
    mapDesc: 'See verified service providers for Jos on the map. Click any pin to contact them.',
    browseAllServices: 'See All Services',
    featuredListings: 'Featured Listings', discoverServices: 'Discover better services from local providers',
    viewAll: 'See All', noListingsYet: 'Nothing dey here yet', beFirstToList: 'Be the first person to list',
    listYourService: 'List Your Service',
    // How it works
    simpleProcess: 'Simple Process', howItWorks: 'How E Dey Work',
    howItWorksDesc: 'Whether you dey find service or you dey offer am — JosMKT make am simple.',
    forCustomers: 'For Customers', forProviders: 'For Providers',
    registerBusinessCta: 'Register Your Business — E Free',
    // Stats
    monthlyViews: 'Monthly Views', businesses: 'Businesses', growthRate: 'Growth Rate', happyCustomers: 'Happy Customers',
    // FAQ
    faqTitle: 'Questions Wey People Dey Ask', faqSubtitle: 'Everything wey you need to know about our services',
    faq1Q: 'How JosMKT go help people see my business?', faq1A: 'We go list your business for our platform wey thousands of buyers for Jos dey see.',
    faq2Q: 'Which promo packages dey available?', faq2A: 'We get Basic (free listing), Standard, and Premium. Contact us for custom packages.',
    faq3Q: 'How I go list my business or service?', faq3A: "Click 'Start Now' for the navigation, fill your business profile, and choose promo plan.",
    faq4Q: 'E get free option?', faq4A: 'Yes! Our Basic listing na free completely.',
    faq5Q: 'I fit track how my business dey perform?', faq5A: 'Sure! Our dashboard go show you views, clicks, inquiries, and engagement.',
    faq6Q: 'Which areas JosMKT dey cover?', faq6A: 'We cover all areas for Jos including Bukuru, Rayfield, Terminus, Lamingo.',
    // CTA
    readyToGrow: 'You Ready to Grow Your Business?', joinThousands: 'Join thousands of service providers for Jos',
    getStartedFree: 'Start Free',
    // Language
    language: 'Language', english: 'English', hausa: 'Hausa', pidgin: 'Pidgin',
    // Footer
    footerDesc: 'Show your business to thousands of buyers for Jos — make dem find you, promote you, get results',
    categories: 'Categories', company: 'Company', contactUs: 'Contact Us',
    electronics: 'Electronics', fashion: 'Fashion', foodCatering: 'Food & Catering', techRepairs: 'Tech & Repairs',
    aboutUs: 'About Us', contact: 'Contact Us', privacy: 'Privacy Policy', terms: 'Terms of Service',
    becomeSeller: 'Become a Seller', allRightsReserved: 'All rights reserved.',
    poweredBy: 'Powered by',
    // Newsletter
    newsletterTitle: 'Stay Updated with JosMKT',
    newsletterDesc: 'Get weekly tips, new service providers, and exclusive deals for your inbox.',
    emailPlaceholder: 'Enter your email address', subscribe: 'Subscribe',
    subscribedSuccess: 'You don subscribe!', noSpam: 'E free forever. No spam. You fit comot anytime.',
    // Services page
    allServices: 'All Services', verifiedProfessionals: 'Verified people for Jos',
    searchServices: 'Search by name, location...', providersFound: 'provider found', providersFoundPlural: 'providers found',
    providersPinned: 'providers pinned', sortedByDistance: 'Sorted by Distance', findNearestToMe: 'Find Nearest to Me',
    noResultsFor: 'No results for', noProvidersIn: 'No providers yet for', clearSearch: 'Clear Search',
    registerYourBusiness: 'Register Your Business', areYouProvider: 'You be service provider?',
    listBusinessDesc: 'Join thousands of professionals wey customers dey find for Jos every day.',
    call: 'Call', whatsapp: 'WhatsApp', verified: 'Verified', kmAway: 'km away',
    back: 'Go Back', location: 'Location', getDirections: 'Get Directions',
    about: 'About', gallery: 'Gallery', needThisService: 'You need this service?',
    contactDirectly: 'Contact', directly: 'directly and start today.',
    providerNotFound: 'Provider no dey',
    // Become seller
    registerBusiness: 'Register Your Business', getStartedOnJosMKT: 'Start for JosMKT',
    becomeSellerdesc: 'List your service or business and thousands of customers for Jos go find you',
    businessName: 'Business / Service Name *', category: 'Category *', describeYourBusiness: 'Describe your business *',
    phoneWhatsapp: 'Phone / WhatsApp *', location: 'Location *', pinExactLocation: 'Pin Your Exact Location',
    pinLocationDesc: 'E go help customers find you on the map', locationPinned: 'Location Pinned ✓', useMyGPS: 'Use My GPS',
    experience: 'Experience', priceRange: 'Price Range', businessLogo: 'Business Logo / Photo',
    workSamples: 'Work Samples / Gallery (optional)', identityVerification: 'Identity Verification (Required)',
    verificationDesc: 'To protect customers from scam, we verify every service provider before approval.',
    govId: 'Government-issued ID', govIdDesc: 'NIN slip, Voter card, Driver license, Passport, or Student ID',
    selfieWithId: 'Selfie with your ID', selfieDesc: 'Take clear photo of yourself holding the same ID',
    uploadYourId: 'Upload your ID', uploadSelfie: 'Take / upload selfie with ID',
    idUploaded: 'ID uploaded ✓', selfieUploaded: 'Selfie uploaded ✓',
    submitting: 'Dey submit...', submitApplication: 'Submit Application',
    applicationSubmitted: 'Application Don Submit!',
    applicationDesc: 'We dey review your business registration. We go contact you once we approve am and your profile go dey live on JosMKT.',
    backToHome: 'Go Back Home', reviewTime: 'We go review your application within 24 hours.',
    selectCategory: 'Pick your category', selectLocation: 'Pick location',
    experiencePlaceholder: 'e.g. 3 years', priceRangePlaceholder: 'e.g. ₦5,000 - ₦50,000',
    uploading: 'Dey upload...',
  }
}

const currentLang = useState<Lang>('lang', () => 'en')

export const useLanguage = () => {
  const t = (key: string): string => {
    return (translations[currentLang.value] as any)[key] ?? (translations.en as any)[key] ?? key
  }
  const setLang = (lang: Lang) => { currentLang.value = lang }
  return { t, currentLang, setLang }
}
